# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ff6b0af2c297aa13fa7d2dc1658eb010"
name = "AI SEO Produktbeskrivelser"
application_url = "https://kyoto-ai-seo-descriptions.jacobfriisstrand.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[distribution]
type = "single_merchant"

[auth]
redirect_urls = [ "https://kyoto-ai-seo-descriptions.jacobfriisstrand.com/auth/callback" ]
